### PR TITLE
Updating Mac instructions for configuring Jagex accounts

### PR DESCRIPTION
**Pull request by jakeleventhal**

### CODE REVIEW

**Comment by Felanbird** [comment]
does this really need a space in-between every step?

**Comment by Adam-** [comment]
I don't think markdown actually renders the space does it? It is probably just the ide formatting it.

**Comment by jakeleventhal** [comment]
@Felanbird it makes the markdown more readable. it does actually space them out

**Comment by jakeleventhal** [comment]
Screenshot 2023-08-29 at 7 26 03 PM
Screenshot 2023-08-29 at 7 26 07 PM

**Comment by jakeleventhal** [comment]
idrc i can revert it if you guys dont like it that way

**Comment by raiyni** [comment]
Personally, spaced out lists like that aren't  great to read from  a UX perspective for reading flow reasons.

**Comment by jakeleventhal** [comment]
@raiyni reverted

**Review by Felanbird — APPROVED** [review]

**Pull request merged**
