### PR TITLE
Host images for wiki pages on this repo

### PR DESCRIPTION
**Pull request by Felanbird**
This PR currently has 131 commits, I cannot guarantee your mental safety if you attempt to review it

TODOs: 

- [x] Get a new wine gif for Cooking.md (this is only an infobox now apparently)
- [x] Go over HTML usage and restore it if images are currently too large
- [x] also check the Prayer orb image size
- [x] new Mage-Arena.md images (i dropped them b/c i'm not fully sure what they're supposed to be)
- [x] some xp-tracker images need to be updated
- [x] Optimize image sizes (webp'd any gif over 4mb)
- [x] more optimizing?

seperate PR:
- [x] remove tree-respawning-timer.md
- [x] remove smoothing-animations.md
- [ ] Check on image sizes of commits already cherry-picked into master

### CODE REVIEW

**Comment by YvesW** [comment]
Assuming I didn't miss it between the 401 changed files, inventory tags should probably use: https://cdn.discordapp.com/attachments/909197220883095653/1147735464455970816/inventory_tags_v2.gif?ex=65f663f2&is=65e3eef2&hm=73f323c9927bdf84167138b28c15d76862c3f2a6003b30df890efb8b0fe39acf&

If we got an infobox/overlay managing page in there, we could use: https://runelite.net/img/blog/1.6.28-Release/infobox.gif

**Comment by raiyni** [comment]
Can these be optimized at all? Some of the images/gifs are particularly fat

**Comment by Felanbird** [comment]
> Can these be optimized at all? Some of the images/gifs are particularly fat

yeah sure, some of them have an ok size for the page, but others are huge and scaled down via HTML, and others are huge and no longer scaled down.

**Comment by Nightfirecat** [comment]
Where is this PR at? Are there more images needing copying, or do we just need to optimize the ones added via this PR?

**Comment by Felanbird** [comment]
Should just be more optimizing and then maybe a manual look-over of all the pages

**Comment by Nightfirecat** [comment]
That should be image optimization taken care of. A few images did seem to gain size, even with `pngcrush` (which has so far been the most reliable tool for reducing image size for me), so we could checkout the previous image versions if they render fine. I guess all that's left now is to do a visual regression test of all the pages.

**Comment by Felanbird** [comment]
301023951-98623406-952e-4d75-856e-1606813cfa23

I finally got the time to go through all the pages and I believe I've fixed all the issues this PR had

I would say "maybe users will report the problems, but none of them noticed all the missing GIFs so we'll see

**Pull request merged**
